/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.beans.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author anhph
 */
public class hienthisach extends javax.swing.JPanel {

    /**
     * Creates new form hienthisach
     */
    public hienthisach() throws Exception {
        initComponents();
        //new hienthisach().setVisible(true);
        //làm mới bảng
        DefaultTableModel tableModel = (DefaultTableModel) tb1.getModel();
        tableModel.setRowCount(0);
        //hiển thị lại
        LoadDBData2JTable();

    }
    private String header[] = {"Mã tài liệu", "Nhà xuất bản", "Số bản phát hành", "tác giả", "số trang"};
    private DefaultTableModel tblModel = new DefaultTableModel(header, 0);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Hiển thị sách");

        tb1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tb1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã tài liệu", "Nhà xuất bản", "Số bản phát hành", "Tác giả", "Số trang"
            }
        ));
        tb1.setRowHeight(30);
        tb1.setRowSorter(tb1.getRowSorter());
        tb1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tb1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tb1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tb1InputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tb1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tb1AncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_tb1AncestorAdded

    private void tb1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tb1InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tb1InputMethodTextChanged
    /**
     * Đọc dữ liệu từ cơ sở dữ liệu rồi dưa lên JTable
     *
     * @throws Exception
     */
    public void LoadDBData2JTable() throws Exception {

        Connection con = getConnection();
        String sql = "Select * from Sach1";
        ResultSet rs = con.createStatement().executeQuery(sql);
        Vector data = null;
        while (rs.next()) {
            data = new Vector();
            data.add(rs.getString("matailieu"));
            data.add(rs.getString("nhaxuatban"));
            data.add(rs.getInt("sobanphathanh"));
            data.add(rs.getString("tg"));
            data.add(rs.getInt("st"));
            // Thêm một dòng vào table model
            tblModel.addRow(data);
        }
        tb1.setModel(tblModel);
        tb1.setAutoCreateRowSorter(true);
        con.close();
    }

    /**
     * Tạo kết nối đền cơ sở dữ liệu
     *
     * @return Connection
     * @throws Exception
     */
    private Connection getConnection() throws Exception {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url = "jdbc:sqlserver://localhost;databaseName=quanlitv";
        Connection con = DriverManager.getConnection(url, "sa", "sa");
        return con;
    }

    public static void main(String[] args) throws Exception {
        new hienthisach().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables
}
