/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anhph
 */
public class hienthitatca extends javax.swing.JPanel {

    /**
     * Creates new form hienthitatca
     */
    public hienthitatca() throws Exception {
        initComponents();
        //làm mới bảng
        DefaultTableModel tableModel = (DefaultTableModel) tb1.getModel();
        tableModel.setRowCount(0);
        //hiển thị lại
        hienthisach();
        //làm mới bảng
        DefaultTableModel tableModel1 = (DefaultTableModel) tb2.getModel();
        tableModel1.setRowCount(0);
        //hiển thị lại
        hienthibao();
        //làm mới bảng
        DefaultTableModel tableModel2 = (DefaultTableModel) tb3.getModel();
        tableModel2.setRowCount(0);
        //hiển thị lại
        hienthitapchi();
    }
    private String header[] = {"Mã tài liệu", "Nhà xuất bản", "Số bản phát hành", "tác giả", "số trang"};
    private DefaultTableModel tblModel = new DefaultTableModel(header, 0);

    public void hienthisach() throws Exception {

        Connection con = getConnection();
        String sql = "Select * from Sach1";
        ResultSet rs = con.createStatement().executeQuery(sql);
        Vector data = null;
        while (rs.next()) {
            data = new Vector();
            data.add(rs.getString("matailieu"));
            data.add(rs.getString("nhaxuatban"));
            data.add(rs.getInt("sobanphathanh"));
            data.add(rs.getString("tg"));
            data.add(rs.getInt("st"));
            // Thêm một dòng vào table model
            tblModel.addRow(data);
        }
        tb1.setModel(tblModel);
        con.close();
    }
//hiển thị báo
    private String header1[] = {"Mã tài liệu", "Nhà xuất bản", "Số bản phát hành", "Ngày phát hành"};
    private DefaultTableModel tblModel1 = new DefaultTableModel(header1, 0);

    public void hienthibao() throws Exception {

        Connection con = getConnection();
        String sql = "Select * from Bao";
        ResultSet rs = con.createStatement().executeQuery(sql);
        Vector data = null;
        while (rs.next()) {
            data = new Vector();
            data.add(rs.getString("matailieu"));
            data.add(rs.getString("nhaxuatban"));
            data.add(rs.getInt("sobanphathanh"));
            data.add(rs.getString("ngayphathanh"));
            // Thêm một dòng vào table model
            tblModel1.addRow(data);
        }
        tb2.setModel(tblModel1);
        con.close();
    }
//hiển thị tất cả
    private String header2[] = {"Mã tài liệu", "Nhà xuất bản", "Số bản phát hành", "Tháng phát hành"};
    private DefaultTableModel tblModel2 = new DefaultTableModel(header2, 0);

    public void hienthitapchi() throws Exception {

        Connection con = getConnection();
        String sql = "Select * from tapchi";
        ResultSet rs = con.createStatement().executeQuery(sql);
        Vector data = null;
        while (rs.next()) {
            data = new Vector();
            data.add(rs.getString("matailieu"));
            data.add(rs.getString("nhaxuatban"));
            data.add(rs.getInt("sophathanh"));
            data.add(rs.getString("thangphathanh"));
            // Thêm một dòng vào table model
            tblModel2.addRow(data);
        }
        tb3.setModel(tblModel2);
        con.close();
    }

    /**
     * Tạo kết nối đền cơ sở dữ liệu
     *
     * @return Connection
     * @throws Exception
     */
    private Connection getConnection() throws Exception {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url = "jdbc:sqlserver://localhost;databaseName=quanlitv";
        Connection con = DriverManager.getConnection(url, "sa", "sa");
        return con;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb3 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setAutoscrolls(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Hiển thị tất cả");

        tb1.setAutoCreateRowSorter(true);
        tb1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb1.setRowSorter(tb1.getRowSorter());
        jScrollPane1.setViewportView(tb1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Sách");

        tb2.setAutoCreateRowSorter(true);
        tb2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb2.setRowSorter(tb2.getRowSorter());
        jScrollPane2.setViewportView(tb2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Báo");

        tb3.setAutoCreateRowSorter(true);
        tb3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb3.setAutoscrolls(true);
        tb3.setRowSorter(tb3.getRowSorter());
        jScrollPane3.setViewportView(tb3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tạp chí");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 762, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tb1;
    private javax.swing.JTable tb2;
    private javax.swing.JTable tb3;
    // End of variables declaration//GEN-END:variables
}
