/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anhph
 */
public class suabao extends javax.swing.JFrame {

    /**
     * Creates new form suabao
     */
    public suabao() throws Exception {
        initComponents();
        //làm mới bảng
        DefaultTableModel tableModel = (DefaultTableModel) tb1.getModel();
        tableModel.setRowCount(0);
        //hiển thị lại
        LoadDBData2JTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtmatailieu = new javax.swing.JTextField();
        txtnhaxuatban = new javax.swing.JTextField();
        txtsobanph = new javax.swing.JTextField();
        txtngayphathanh = new javax.swing.JTextField();
        btncapnhat = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtmatailieu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtnhaxuatban.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtsobanph.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtngayphathanh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btncapnhat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncapnhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gpa-icon.png"))); // NOI18N
        btncapnhat.setText("Cập nhật");
        btncapnhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncapnhatMouseClicked(evt);
            }
        });
        btncapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapnhatActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout-icon-16.png"))); // NOI18N
        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Mã tài liệu");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nhà xuất bản");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Số bản phát hành");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Ngày phát hành");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btncapnhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtsobanph, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnhaxuatban, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmatailieu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtngayphathanh, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmatailieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnhaxuatban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsobanph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtngayphathanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncapnhat)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapnhatActionPerformed
        if (txtmatailieu.getText().isEmpty()) {
            MessageDialogHelper.showErrorDialog(this, "Lỗi", "Vui lòng điền mã tài liệu");
            txtmatailieu.requestFocus();
            return; // Thoát khỏi xử lý không thực hiện các lệnh tiếp theo
        }
        // Nếu không nhập tiêu đề (Title)
        if (txtnhaxuatban.getText().isEmpty()) {
            MessageDialogHelper.showErrorDialog(this, "Lỗi", "Vui lòng điền nhà xuất bản");
            txtnhaxuatban.requestFocus();
            return; // Thoát khỏi xử lý không thực hiện các lệnh tiếp theo
        }
        if (txtsobanph.getText().isEmpty()) {
            MessageDialogHelper.showErrorDialog(this, "Lỗi", "Vui lòng điền số bản phát hành");
            txtsobanph.requestFocus();
            return; // Thoát khỏi xử lý không thực hiện các lệnh tiếp theo
        }
        if (txtngayphathanh.getText().isEmpty()) {
            MessageDialogHelper.showErrorDialog(this, "Lỗi", "Vui lòng ngày phát hành");
            txtngayphathanh.requestFocus();
            return; // Thoát khỏi xử lý không thực hiện các lệnh tiếp theo
        }

        // Hiển thị hộp thoại xác nhận có muốn lưu hay không?
        int ret = JOptionPane.showConfirmDialog(this, "Bạn có muốn cập nhật?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        // Trường hợp không lưu
        if (ret != JOptionPane.YES_OPTION) {
            return; // Thoát khỏi phương thức
        }
        // Câu lệnh insert
        try {
            Bao a = new Bao();
            a.setMatailieu(txtmatailieu.getText());
            a.setNhaxuatban(txtnhaxuatban.getText());
            a.setSobanphathanh(Integer.parseInt(txtsobanph.getText()));

            a.setNgayphathanh(txtngayphathanh.getText());

            baodao dao = new baodao();

            dao.update(a);
            JOptionPane.showMessageDialog(this, "Cập nhật thành công báo có mã " + txtmatailieu.getText());
            //làm mới bảng
            DefaultTableModel tableModel = (DefaultTableModel) tb1.getModel();
            tableModel.setRowCount(0);
            //hiển thị lại
            LoadDBData2JTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Có lỗi " + e.getMessage());
            e.printStackTrace();
        }            // TODO add your handling code here:
    }//GEN-LAST:event_btncapnhatActionPerformed

    private void btncapnhatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncapnhatMouseClicked
        int row = tb1.getSelectedRow();
        if (row >= 0) {
            txtmatailieu.setText(tb1.getValueAt(row, 0).toString());
            txtnhaxuatban.setText(tb1.getValueAt(row, 1).toString());
            txtsobanph.setText(tb1.getValueAt(row, 2).toString());
            txtngayphathanh.setText(tb1.getValueAt(row, 3).toString());

        }              // TODO add your handling code here:
    }//GEN-LAST:event_btncapnhatMouseClicked

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        int row = tb1.getSelectedRow();
        if (row >= 0) {
            txtmatailieu.setText(tb1.getValueAt(row, 0).toString());
            txtnhaxuatban.setText(tb1.getValueAt(row, 1).toString());
            txtsobanph.setText(tb1.getValueAt(row, 2).toString());
            txtngayphathanh.setText(tb1.getValueAt(row, 3).toString());

        }           // TODO add your handling code here:
    }//GEN-LAST:event_tb1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.hide();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    private String header[] = {"Mã tài liệu", "Nhà xuất bản", "Số bản phát hành", "Ngày phát hành"};
    private DefaultTableModel tblModel = new DefaultTableModel(header, 0);

    public void LoadDBData2JTable() throws Exception {

        Connection con = getConnection();
        String sql = "Select * from Bao";
        ResultSet rs = con.createStatement().executeQuery(sql);
        Vector data = null;
        while (rs.next()) {
            data = new Vector();
            data.add(rs.getString("matailieu"));
            data.add(rs.getString("nhaxuatban"));
            data.add(rs.getInt("sobanphathanh"));
            data.add(rs.getString("ngayphathanh"));
            // Thêm một dòng vào table model
            tblModel.addRow(data);
        }
        tb1.setModel(tblModel);
        con.close();
    }

    /**
     * Tạo kết nối đền cơ sở dữ liệu
     *
     * @return Connection
     * @throws Exception
     */
    private Connection getConnection() throws Exception {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url = "jdbc:sqlserver://localhost;databaseName=quanlitv";
        Connection con = DriverManager.getConnection(url, "sa", "sa");
        return con;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(suabao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(suabao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(suabao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(suabao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new suabao().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(suabao.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncapnhat;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tb1;
    private javax.swing.JTextField txtmatailieu;
    private javax.swing.JTextField txtngayphathanh;
    private javax.swing.JTextField txtnhaxuatban;
    private javax.swing.JTextField txtsobanph;
    // End of variables declaration//GEN-END:variables
}
