/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anhph
 */
public class suatapchi extends javax.swing.JFrame {

    /**
     * Creates new form suatapchi
     */
    public suatapchi() throws Exception {
        initComponents();
        //làm mới bảng
        DefaultTableModel tableModel = (DefaultTableModel) tb1.getModel();
        tableModel.setRowCount(0);
        //hiển thị lại
        LoadDBData2JTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtmatailieu = new javax.swing.JTextField();
        txtnhaxuatban = new javax.swing.JTextField();
        txtsobanphathanh = new javax.swing.JTextField();
        txtsophathanh = new javax.swing.JTextField();
        txtthangphathanh = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtmatailieu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtnhaxuatban.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtsobanphathanh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtsophathanh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtthangphathanh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gpa-icon.png"))); // NOI18N
        jButton1.setText("Cập nhật");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mã tài liệu");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nhà xuất bản");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Số bản phát hành");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Số phát hành");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tháng phát hành");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Login-icon-16.png"))); // NOI18N
        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmatailieu)
                            .addComponent(txtnhaxuatban)
                            .addComponent(txtsobanphathanh)
                            .addComponent(txtsophathanh)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jButton1)
                        .addGap(9, 9, 9)
                        .addComponent(txtthangphathanh))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(22, 22, 22)))
                .addGap(177, 177, 177))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnhaxuatban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(txtsobanphathanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtmatailieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(txtsophathanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(txtthangphathanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        int row = tb1.getSelectedRow();
        if (row >= 0) {
            txtmatailieu.setText(tb1.getValueAt(row, 0).toString());
            txtnhaxuatban.setText(tb1.getValueAt(row, 1).toString());
            txtsobanphathanh.setText(tb1.getValueAt(row, 2).toString());
            txtsophathanh.setText(tb1.getValueAt(row, 3).toString());
            txtthangphathanh.setText(tb1.getValueAt(row, 4).toString());

        }          // TODO add your handling code here:
    }//GEN-LAST:event_tb1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtmatailieu.getText().isEmpty()) {
            MessageDialogHelper.showErrorDialog(this, "Lỗi", "Vui lòng điền mã tài liệu");
            txtmatailieu.requestFocus();
            return; // Thoát khỏi xử lý không thực hiện các lệnh tiếp theo
        }
        // Nếu không nhập tiêu đề (Title)
        if (txtnhaxuatban.getText().isEmpty()) {
            MessageDialogHelper.showErrorDialog(this, "Lỗi", "Vui lòng điền nhà xuất bản");
            txtnhaxuatban.requestFocus();
            return; // Thoát khỏi xử lý không thực hiện các lệnh tiếp theo
        }
        if (txtsobanphathanh.getText().isEmpty()) {
            MessageDialogHelper.showErrorDialog(this, "Lỗi", "Vui lòng điền số bản phát hành");
            txtsobanphathanh.requestFocus();
            return; // Thoát khỏi xử lý không thực hiện các lệnh tiếp theo
        }
        if (txtsophathanh.getText().isEmpty()) {
            MessageDialogHelper.showErrorDialog(this, "Lỗi", "Vui lòng điền số phát hành");
            txtsophathanh.requestFocus();
            return; // Thoát khỏi xử lý không thực hiện các lệnh tiếp theo
        }
        if (txtthangphathanh.getText().isEmpty()) {
            MessageDialogHelper.showErrorDialog(this, "Lỗi", "Vui lòng tháng phát hành");
            txtthangphathanh.requestFocus();
            return; // Thoát khỏi xử lý không thực hiện các lệnh tiếp theo
        }

        // Hiển thị hộp thoại xác nhận có muốn lưu hay không?
        int ret = JOptionPane.showConfirmDialog(this, "Bạn có muốn cập nhật?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        // Trường hợp không lưu
        if (ret != JOptionPane.YES_OPTION) {
            return; // Thoát khỏi phương thức
        }
        // Câu lệnh insert
        try {
            TapChi a = new TapChi();
            a.setMatailieu(txtmatailieu.getText());
            a.setNhaxuatban(txtnhaxuatban.getText());
            a.setSobanphathanh(Integer.parseInt(txtsobanphathanh.getText()));
            a.setSobanphathanh(Integer.parseInt(txtsobanphathanh.getText()));
            a.setSophathanh(Integer.parseInt(txtsophathanh.getText()));
            a.setThangphathanh(txtthangphathanh.getText());

            tapchidao dao = new tapchidao();

            dao.update(a);
            JOptionPane.showMessageDialog(this, "Cập nhật thành công tạp chí có mã " + txtmatailieu.getText());
            //làm mới bảng
            DefaultTableModel tableModel = (DefaultTableModel) tb1.getModel();
            tableModel.setRowCount(0);
            //hiển thị lại
            LoadDBData2JTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Có lỗi " + e.getMessage());
            e.printStackTrace();
        }            // TODO ad        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.hide();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(suatapchi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(suatapchi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(suatapchi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(suatapchi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new suatapchi().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(suatapchi.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    private String header[] = {"Mã tài liệu", "Nhà xuất bản", "Số bản phát hành", "Số phát hành", "Tháng phát hành"};
    private DefaultTableModel tblModel = new DefaultTableModel(header, 0);

    public void LoadDBData2JTable() throws Exception {

        Connection con = getConnection();
        String sql = "Select * from tapchi";
        ResultSet rs = con.createStatement().executeQuery(sql);
        Vector data = null;
        while (rs.next()) {
            data = new Vector();
            data.add(rs.getString("matailieu"));
            data.add(rs.getString("nhaxuatban"));
            data.add(rs.getInt("sobanphathanh"));
            data.add(rs.getInt("sophathanh"));
            data.add(rs.getString("thangphathanh"));
            // Thêm một dòng vào table model
            tblModel.addRow(data);
        }
        tb1.setModel(tblModel);
        con.close();
    }

    /**
     * Tạo kết nối đền cơ sở dữ liệu
     *
     * @return Connection
     * @throws Exception
     */
    private Connection getConnection() throws Exception {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url = "jdbc:sqlserver://localhost;databaseName=quanlitv";
        Connection con = DriverManager.getConnection(url, "sa", "sa");
        return con;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb1;
    private javax.swing.JTextField txtmatailieu;
    private javax.swing.JTextField txtnhaxuatban;
    private javax.swing.JTextField txtsobanphathanh;
    private javax.swing.JTextField txtsophathanh;
    private javax.swing.JTextField txtthangphathanh;
    // End of variables declaration//GEN-END:variables
}
