/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anhph
 */
public class timkiem extends javax.swing.JPanel {

    /**
     * Creates new form timkiem
     */
    public timkiem() {
        initComponents();
        tblModel = (DefaultTableModel) tb1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txttimkiem = new javax.swing.JTextField();
        btntimsach = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Tìm kiếm");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("Nhập nội dung tìm kiếm");

        btntimsach.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btntimsach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sach.png"))); // NOI18N
        btntimsach.setText("Tìm kiếm sách");
        btntimsach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimsachActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bao.png"))); // NOI18N
        jButton2.setText("Tìm kiếm báo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tapchi.png"))); // NOI18N
        jButton3.setText("Tìm kiếm tạp chí");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(tb1);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 102, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout-icon-16.png"))); // NOI18N
        jButton4.setText("Thoát");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btntimsach)
                                        .addGap(73, 73, 73)
                                        .addComponent(jButton2)
                                        .addGap(105, 105, 105)
                                        .addComponent(jButton3)
                                        .addGap(85, 85, 85)
                                        .addComponent(jButton4))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(294, 294, 294)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntimsach)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
    List<Sach> listS = new ArrayList<>();
    List<Bao> listB = new ArrayList<>();
    List<TapChi> listC = new ArrayList<>();
    private String header[] = {"Mã tài liệu", "Nhà xuất bản", "Số bản phát hành", "tác giả", "số trang"};
    private DefaultTableModel tblModel1 = new DefaultTableModel(header, 0);
    private void btntimsachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimsachActionPerformed

        if (txttimkiem.getText().isEmpty()) {
            MessageDialogHelper.showErrorDialog(this, "Lỗi", "Vui lòng nhập nội dung tìm kiếm");
            txttimkiem.requestFocus();
            return; // Thoát khỏi xử lý không thực hiện các lệnh tiếp theo
        }

// Câu lệnh insert
        try {
            tb1.setModel(tblModel1);
            timkiemdao a = new timkiemdao();
            listS = timkiemdao.FindSach(txttimkiem.getText(), txttimkiem.getText(), txttimkiem.getText());
            tblModel1.setRowCount(0);
            for (Sach sach : listS) {
                //String header[] = {"Mã tài liệu", "Nhà xuất bản", "Số bản phát hành", "tác giả", "số trang"};
                //tblModel.header;

                tblModel1.addRow(new Object[]{sach.getMatailieu(), sach.getNhaxuatban(), sach.getSobanphathanh(), sach.getTg(), sach.getSt()});
            }

//            Timsach(a);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Có lỗi " + e.getMessage());
            e.printStackTrace();
        }    // TODO add your handling code here:
    }//GEN-LAST:event_btntimsachActionPerformed
    private String header1[] = {"Mã tài liệu", "Nhà xuất bản", "Số bản phát hành", "ngày phát hành"};
    private DefaultTableModel tblModel2 = new DefaultTableModel(header1, 0);
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (txttimkiem.getText().isEmpty()) {
            MessageDialogHelper.showErrorDialog(this, "Lỗi", "Vui lòng nhập nội dung tìm kiếm");
            txttimkiem.requestFocus();
            return; // Thoát khỏi xử lý không thực hiện các lệnh tiếp theo
        }

// Câu lệnh insert
        try {
            tb1.setModel(tblModel2);
            timkiemdao a = new timkiemdao();
            listB = a.FindBao(txttimkiem.getText(), txttimkiem.getText(), txttimkiem.getText(), txttimkiem.getText());
            tblModel2.setRowCount(0);
            for (Bao bao : listB) {
                //String header[] = {"Mã tài liệu", "Nhà xuất bản", "Số bản phát hành", "tác giả", "số trang"};
                //tblModel.header;
                tblModel2.addRow(new Object[]{bao.getMatailieu(), bao.getNhaxuatban(), bao.getSobanphathanh(), bao.getNgayphathanh()});
            }

//            Timsach(a);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Có lỗi " + e.getMessage());
            e.printStackTrace();
        }    // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    private String header2[] = {"Mã tài liệu", "Nhà xuất bản", "Số bản phát hành", "số phát hành", "tháng phát hành"};
    private DefaultTableModel tblModel3 = new DefaultTableModel(header2, 0);
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (txttimkiem.getText().isEmpty()) {
            MessageDialogHelper.showErrorDialog(this, "Lỗi", "Vui lòng nhập nội dung tìm kiếm");
            txttimkiem.requestFocus();
            return; // Thoát khỏi xử lý không thực hiện các lệnh tiếp theo
        }

// Câu lệnh insert
        try {
            tb1.setModel(tblModel3);
            timkiemdao a = new timkiemdao();
            listC = timkiemdao.FindTapchi(txttimkiem.getText(), txttimkiem.getText(), txttimkiem.getText(), txttimkiem.getText(), txttimkiem.getText());
            tblModel3.setRowCount(0);
            for (TapChi tc : listC) {
                //String header[] = {"Mã tài liệu", "Nhà xuất bản", "Số bản phát hành", "tác giả", "số trang"};
                //tblModel.header;

                tblModel3.addRow(new Object[]{tc.getMatailieu(), tc.getNhaxuatban(), tc.getSobanphathanh(), tc.getSophathanh(), tc.getThangphathanh()});
            }

//            Timsach(a);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Có lỗi " + e.getMessage());
            e.printStackTrace();
        }    // TODO add         // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private DefaultTableModel tblModel;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntimsach;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb1;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
